### ISSUE TITLE
Add support for routeType.tsx ?

### ISSUE THREAD

**Issue by bring-shrubbery** [ethanniser/next-typesafe-url#101]
I've just spend a full day trying to debug why the dynamic route is not being generated. Restructured my whole localisation setup, since I thought that was the problem.

Turns out I've named my `routeType.tsx` instead of `routeType.ts`.

## Proposed solution

Maybe CLI should also include `.tsx` files? Would save a lot of time for someone other than me 😆

**Comment by ethanniser** [comment]
Happy to accept a pr
