### ISSUE TITLE
"ReferenceError: require is not defined" since next15-canary150 in dev mode with turbo

### ISSUE THREAD

**Issue by nctay** [ethanniser/next-typesafe-url#104]
@ethanniser First of all, thanks for this great tool! 

I know, that's not your issue, but maybe you have some thoughts why it happens:

### Link to the code that reproduces this issue
https://github.com/nctay/NextJS-canary-require-issue

### To Reproduce
Start dev with --turbo
Get error ReferenceError: require is not defined

### Nextjs issue
https://github.com/vercel/next.js/issues/70186

**Comment by ethanniser** [comment]
it works without turbo though?

**Comment by nctay** [comment]
It seems like the Turbopack team is aware of the issue and is working on fixing it. Yeah it does work with turbo disabled. Thanks for response, closing this issue.
