### ISSUE TITLE
Possible to allow the setting of a filename in the cli to be used in place of routeType.ts?

### ISSUE THREAD

**Issue by JasonPaff** [ethanniser/next-typesafe-url#112]
I have no idea how hard or easy it would be to do this, but I think it would be great if we had the option to set the filename this tool looks for from the CLI or something. It would be nice to be able to name my file route-type.ts instead of routeType.ts to match the rest of my app.

**Comment by ethanniser** [comment]
sure, could be added as a cli flag
open to prs
